Matrix Vault
virto-network/libwallet pull request #23
Opened 2022-11-28 04:24 UTC by S0c5

This PR implements the Matrix vault backend for libwallet

[ ] Fix the secret data type 
```
 // from
    "encrypted": {
            "iv": "q8yMRCfoRetLFpEdFKx/2Q==",
            "ciphertext": "fLuKbG23S5adocc8Y6VusPWYKe9CDfhZlmefORye91KXxfoO5aYWwM2jYko=",
            "mac": "CUoero9f+2pdoLBSqGkKTTmH4kDcyra3pU2p3WgH9GI="
    }
to 
    "encrypted": {
        "[key-used-to-encrypt]": {
            "iv": "q8yMRCfoRetLFpEdFKx/2Q==",
            "ciphertext": "fLuKbG23S5adocc8Y6VusPWYKe9CDfhZlmefORye91KXxfoO5aYWwM2jYko=",
            "mac": "CUoero9f+2pdoLBSqGkKTTmH4kDcyra3pU2p3WgH9GI="
        }
    }
```

2022-12-12 01:28 UTC, S0c5 commented
Any comments on this?

2022-12-16 21:45 UTC, olanod requested changes

2022-12-16 21:45 UTC, olanod commented on Cargo.toml
> +matrix-sdk = { version ="0.4.1", optional = true }
Not being used right?

2022-12-16 21:45 UTC, olanod commented on examples/persisted_in_matrix.rs
> +    let password = env::args().nth(4).unwrap();
✂️ ?

2022-12-16 21:45 UTC, olanod commented on src/vault/matrix/vault.rs
> +impl core::fmt::Display for Error {
If you are including `thiserror` as dependency you should use it to avoid implementing error messages manually.

2022-12-16 21:45 UTC, olanod commented on src/vault/matrix/vault.rs
> +const SECRET_NAME: &str = "id-seed-10";
is this `SECRET_NAME` based on a convention or something?

2022-12-16 21:45 UTC, olanod commented on src/vault/matrix/vault.rs
> +            .map_err(|_| Error::ErrorGettingSecret);
You are mapping the error but not propagating it with `?`, instead in the next block the error is immediately handled(ignored) by generating, saving and returning a new key. Creating a new key when none exists is good(but isn't that what the `Option` is for?) but I think the storage might fail for more reasons(e.g. network) so we should detect what kind of errors we cannot recover from and propagate them, and for the ones that are not critical we do the key generation. As of now if there's something like a network or server error the program will just crash when saving the secret.

2022-12-16 21:45 UTC, olanod commented on src/vault/matrix/vault.rs
> +            .map_err(|_| Error::ErrorGettingSecret);
TL;DR. we can probably delete this line and handle stuff in the match

2022-12-16 21:45 UTC, olanod commented on src/vault/matrix/vault.rs
> +                let key = seed.unwrap();
This unwraps an option right? I think the `Option` is there to signal that it didn't find the secret so we definitely need to handle that.  
e.g. 
```
Ok(Some(seed)) => Ok(cb(&RootAccount::from_bytes(&seed))),
Ok(None) | Err(SomeAcceptableError) => {},// key generation
Err(_) => Err(Error::ErrorGettingSecret)
```

2022-12-16 21:45 UTC, olanod commented on src/vault/matrix/storage.rs
> +use std::convert::TryFrom;
In no_std libraries and for consistency is better to explicitly use `core` or `alloc` unless it's something that only lives in `std`
```suggestion
use core::convert::TryFrom;
```

2022-12-16 21:45 UTC, olanod commented on src/vault/matrix/storage.rs
> +    server: String,
Perhaps the `MatrixUserCreeds` can be in this module and used here instead, WDYT? aaand it would be a nice lifetimes exercise to keep a borrow of that struct to avoid coping data into this struct.

2022-12-16 21:45 UTC, olanod commented on src/vault/matrix/vault.rs
> +    pub username: String,
Here's another interesting no allocation exercise for extra points, what about storing a MXID of the form `@username:server.foo` which is the fully qualified and likely the common way the credentials are going to be provided by users, we can create a unit struct that wraps the mxid string slice (e.g. `MxId<'a>(&'a str)`) and give it the `uname(&self) -> &str` and `server(&self) -> &str` methods that parse the contents lazily returning also a `&str`. Since the data that make up the username and server are already there in the provided str we can return slices of that str without having to allocate new Strings

2022-12-16 21:45 UTC, olanod commented on src/vault/matrix/storage.rs
> +                .set_base_url(Url::parse(&format!("https://{}", server)).unwrap())
If we assume the URL is valid then `.expect("valid URL")` works better

2022-12-16 21:45 UTC, olanod commented on src/vault/matrix/storage.rs
> +                .unwrap(),
again better to `expect` that building the client won't fail.

2022-12-16 21:45 UTC, olanod commented on src/vault/matrix/storage.rs
> +struct MatrixKeyOps {}
An empty struct with only static methods that isn't implementing any trait doesn't make much sense as it is effectively just a namespace, we already `mod`ules for that ;)

2022-12-16 21:45 UTC, olanod commented on src/vault/matrix/storage.rs
> +            .unwrap();
```suggestion
            .map_err(|_| MatrixError::InvalidStorageKey)?;
```

2022-12-16 21:45 UTC, olanod commented on src/vault/matrix/storage.rs
> +    pub fn decode_recovery_key(recovery_key: &str) -> Result<MatrixStorageKey> {
Should probably be a "constructor" of `MatrixStorageKey`, e.g. `from_recovery_key`?

2022-12-16 21:45 UTC, olanod commented on src/vault/matrix/storage.rs
> +            println!("wrong prefix");
These `println!`, we either remove them, add extra context to the error or turn them into logs

2022-12-16 21:45 UTC, olanod commented on src/vault/matrix/storage.rs
> +struct MatrixKeyOps {}
I also see that mose methods in the "fake module" should rather belong to the impl block of `MatrixStorageKey`

2022-12-16 21:45 UTC, olanod commented on src/vault/matrix/storage.rs
> +    fn get_key_from_passphrase(passphrase: &str, key_data: &KeyData) -> Result<MatrixStorageKey> {
`MatrixStorageKey::from_passphrase` fits better and as we are constructing a `MatrixStorageKey` that can hold the `KeyData` why not take ownership of the data :)

2022-12-16 21:45 UTC, olanod commented on src/vault/matrix/storage.rs
> +    pub fn from_passphrase(passphrase: &str, salt: &str, rounds: u32) -> MatrixStorageKey {
This one could be an inline function in the previous function just to hash/derive the key.
```
// ... body of the function
// inside the function
#[inline]
fn derive_key(passphrase: &str, salt: &str, rounds: u32) -> [u8; 32] {}
```

2022-12-16 21:45 UTC, olanod commented on src/vault/matrix/storage.rs
> +    // }
✂️

2022-12-16 21:45 UTC, olanod commented on src/vault/matrix/storage.rs
> +    fn decrypt_secret(
`EncryptionKeys::decrypt(&self, secret: &StorageSecret)`)` ?

2022-12-16 21:45 UTC, olanod commented on src/vault/matrix/storage.rs
> +    fn derive_keys(storage_key: &MatrixStorageKey) -> Result<Keys> {
`MatrixStorageKey::derive_encryption_keys(&self) -> Result<EncryptionKeys>` ?

2022-12-16 21:45 UTC, olanod commented on src/vault/matrix/storage.rs
> +    fn encrypt_bytes(bytes: &[u8], keys: &Keys, nonce: &[u8]) -> Result<Encrypted> {
`EncryptionKeys::encrypt(&self, bytes: &[u8], nonce: &[u8]) -> Result<Encrypted>` ?

2022-12-16 21:45 UTC, olanod commented on src/vault/matrix/storage.rs
> +    fn validate_key(storage_key: &MatrixStorageKey) -> Result<()> {
`MatrixStorageKey::validate(&self) -> Result<()>` ?

2022-12-16 21:45 UTC, olanod commented on src/vault/matrix/storage.rs
> +        storage_key.key_data = self.get_storage_key_data().await.map(|a| Some(a))?;
I don't think this second call to `get_storage_key_data` is needed specially if we can change the `from_passphrase` to take ownership of `key_data` and assign it already to the `storage_key`

2022-12-16 21:45 UTC, olanod commented on src/vault/matrix/storage.rs
> +        // TODO: unwrap key name from get secret and look in the storages of keys
✂️

2022-12-21 23:32 UTC, S0c5 commented on src/vault/matrix/vault.rs
> +const SECRET_NAME: &str = "id-seed-10";
don't know if there is a convention out there for something like the "id-seed" :(, that's the name we decided for the secret that we want to store in our SSSS, but I forgot unfortunately to delete the -10

2023-01-03 01:54 UTC, S0c5 commented
Hey @olanod !  can you take a look over the last changes I made, looking forward to merge this PR

2023-01-04 10:02 UTC, olanod commented
> Hey @olanod ! can you take a look over the last changes I made, looking forward to merge this PR

Conflicts? :)

2023-01-06 21:54 UTC, olanod requested changes
One last bit before merge :)

2023-01-06 21:54 UTC, olanod commented on src/vault/matrix/vault.rs
> +                    .unwrap();
How should we handle this to not unwrap? can we test this? when does it happen?

2023-11-16 18:33 UTC, closed without merging